# Generated by Django 3.2.19 on 2023-12-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('annee_construction', models.DateField(verbose_name='annee_construction')),
                ('cylindree', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=200)),
            ],
        ),
    ]
